const ENERGIA_ESTADOS = {
  AC: { nome: "Acre", kwh: 0.72 },
  AL: { nome: "Alagoas", kwh: 0.81 },
  AP: { nome: "Amapá", kwh: 0.65 },
  AM: { nome: "Amazonas", kwh: 0.68 },
  BA: { nome: "Bahia", kwh: 0.79 },
  CE: { nome: "Ceará", kwh: 0.83 },
  DF: { nome: "Distrito Federal", kwh: 0.71 },
  ES: { nome: "Espírito Santo", kwh: 0.78 },
  GO: { nome: "Goiás", kwh: 0.74 },
  MA: { nome: "Maranhão", kwh: 0.76 },
  MT: { nome: "Mato Grosso", kwh: 0.73 },
  MS: { nome: "Mato Grosso do Sul", kwh: 0.72 },
  MG: { nome: "Minas Gerais", kwh: 0.80 },
  PA: { nome: "Pará", kwh: 0.69 },
  PB: { nome: "Paraíba", kwh: 0.82 },
  PR: { nome: "Paraná", kwh: 0.70 },
  PE: { nome: "Pernambuco", kwh: 0.84 },
  PI: { nome: "Piauí", kwh: 0.85 },
  RJ: { nome: "Rio de Janeiro", kwh: 0.90 },
  RN: { nome: "Rio Grande do Norte", kwh: 0.86 },
  RS: { nome: "Rio Grande do Sul", kwh: 0.75 },
  RO: { nome: "Rondônia", kwh: 0.67 },
  RR: { nome: "Roraima", kwh: 0.63 },
  SC: { nome: "Santa Catarina", kwh: 0.73 },
  SP: { nome: "São Paulo", kwh: 0.76 },
  SE: { nome: "Sergipe", kwh: 0.80 },
  TO: { nome: "Tocantins", kwh: 0.74 }
};
